### ISSUE TITLE
enable plugin change time of save

### ISSUE THREAD

**Issue by Kristey** [jamesfzhang/auto-save#12]
Hello 
Thanks for your plugin.
I am not succeeding in activate.
But also liked that he writes only 5 in 5 minutes.
This is possible by changing some parameter?

**Comment by Melvillian** [comment]
Kristey,

I had this same problem and find a solution.

You can change this yourself by changing a parameter within the "auto_save.sublime-settings" file. I'm doing this on a Mac so it may be different if you're running a different OS, but while you're in Sublime Text 2 go to

Sublime Text 2 > Preferences > Browse Packages

and then go to the "auto_save" directory. In there you'll find  "auto_save.sublime-settings" and you can change the "auto_save_delay_in_seconds" value to whatever value you want. Be sure to save once you've made the change.
