### ISSUE TITLE
I want: By default, auto-save is enabled.

### ISSUE THREAD

**Issue by fzx** [jamesfzhang/auto-save#15]

**Comment by daconex** [comment]
Bump. I'd like this feature as well.

**Comment by sinaru** [comment]
You can do this with configuration update. 
In Sublime Text 3 go to "_Preference > Package Settings > auto-save > Settings - User_"
Then set value `"auto_save_on_modified": true`
Restart sublime text. Now when you make any change to files, the save will be invoked.
Note: If you check auto-save settings - default, you will note that _auto_save_on_modified_ is set to false meaning by default this is turned off. 
Let me know if this is what you needed.

**Comment by daconex** [comment]
@sinaru Exactly what I was looking for! Thanks :smiley:
