### ISSUE TITLE
CAN'T GET IT TO WORK! What might I be doing wrong?!

### ISSUE THREAD

**Issue by ttcg52** [jamesfzhang/auto-save#22]
I have done the following, as instructed:

1. Pasted these lines into Settings —User:
`"auto_save_on_modified": true,`
`"auto_save_delay_in_seconds": 0.1,` 

2. Pasted this line into Key Bindings — User:
`{ "keys": ["ctrl+shift+s"], "command": "auto_save" },`

3. Copied "auto_save.py" into Sublime's program folder.

4. Tried pressing the shortcut Ctrl+Shift+S several times to enable it, but nothing seems to happen!

Can anyone please tell me, what am I doing wrong here? Please help! I'm a noob in coding! :/

**Comment by scholer** [comment]
Regarding (3) **"Copied "auto_save.py" into Sublime's program folder."** - what do you mean exactly? auto_save is installed like any other plugin. If you post what you did in more detail including the entire content of your settings and key-bindings files, we will have an easier time figuring out what is wrong.
