### ISSUE TITLE
Use debouncing to save only when necessary

### ISSUE THREAD

**Issue by jesusreal** [jamesfzhang/auto-save#28]
First of all, thanks a lot for the plugin. It is very useful and I see good improvements coming :-)
As a frontend developer, I would like auto-save to save my work as fast as possible, but I believe it would be much more sensible and efficient if it used a debounce function, i.e., if it only saves the file after I stop typing for the time set in "auto_save_delay_in_seconds".

**Comment by jamesfzhang** [comment]
Save is debounced. See https://github.com/jamesfzhang/auto-save/blob/master/auto_save.py#L77-L90

**Comment by jesusreal** [comment]
Yes, sorry I didn't notice before.
