### ISSUE TITLE
Going back to start of line when saving on empty line

### ISSUE THREAD

**Issue by jesusreal** [jamesfzhang/auto-save#29]
I have been using the plugin in the last weeks and I really like it and appreciate your work, but I see something completely annoying. When I am in a new line, apply some tab and then for some reason I write nothing, on save the cursor goes back to the start of the line (it does not state in the position I set). It would be great if you could fix that, because I ended up disabling the plugin for this reason. Thanks a lot.

Modifying the value of "auto_save_delay_in_seconds" is not a valid solution in my humble opinion, since many times I want files to be saved very fast, so that everything is live reloaded in the browser as fast as possible and I don't have to wait.

**Comment by jamesfzhang** [comment]
Do you have `"trim_trailing_white_space_on_save": true` in your user or default settings?

**Comment by jesusreal** [comment]
Hi @jamesfzhang, thanks for the quick response. Yes, I didn't realise about it. I changed this flag to false and I that solved my problem.
