### ISSUE TITLE
have auto indent alongside auto save

### ISSUE THREAD

**Issue by molikh** [jamesfzhang/auto-save#30]
thanks for your prefect package
is there any way to have auto-indent alongside auto save.
simply in the same time before save file indent it ( like press f12 for indenting).

**Comment by jamesfzhang** [comment]
This seems to be out of this package's scope.

**Comment by molikh** [comment]
yes , is there simple way to do that by my own?

**Comment by jamesfzhang** [comment]
Sublime Text should auto-indent based on what language you have the file set to...

**Comment by molikh** [comment]
thanks
