### ISSUE TITLE
Autosave not working

### ISSUE THREAD

**Issue by tiffanyhaltom** [jamesfzhang/auto-save#34]
I installed auto-save to Sublime Text Build 3126 a few months back and it randomly stopped working. 

"save_on_focus_lost" is set to true in user settings.

**Comment by Avinash-Bhat** [comment]
I think it's better to run your own plugin for this like mentioned in https://forum.sublimetext.com/t/auto-save-on-every-keypress/6055/13.

**Comment by scholer** [comment]
I'm using Sublime Text 3 Build 3126, and it works fine here. 

Do you get any errors in the console?

Note that auto-saving on every keypress can make the editor quite slow. The nice thing about this auto-save package is that is registers all keypresses, but only saves once per predefined time interval.

**Comment by jamesfzhang** [comment]
@Avinash-Bhat Sorry I haven't been able to give this project the attention it deserves. It's been fairly stable with a few improvements made over the past year and half by community members @scholer so I wouldn't consider it abandoned :)

@tiffanyhaltom What errors do you see in the ST console?
