### ISSUE TITLE
Autosave:  Please provide option to be on by default

### ISSUE THREAD

**Issue by quantbo** [jamesfzhang/auto-save#36]
When I first bring up ST3 Autosave is by default turned off. I take it from your notes that this is considered a feature, not a bug. I take issue with this design decision. If a user has taken the trouble to install Autosave it's because they want it's functionality. It's a nuisance to have to turn on Autosave each time ST3 is activated. To make everyone happy, please provide an option to allow Autosave to be on by default for those who prefer this way of working.

My platform: ST3 Build 3126, running on Windows 7 and 10.

**Comment by luxe** [comment]
I completely agree.

**Comment by luxe** [comment]
actually, this can be adjusted by adding:  
```
{
"auto_save_on_modified": true
}
```
into Packages/User/auto_save.sublime-settings

**Comment by quantbo** [comment]
Thank you, luxe. Your fix works. Just tested it out.
